# Site settings
title:
  en: "Jonathan Senecal :: Resume"
  fr: "Jonathan Senecal :: Page perso"
description:
  en: Jonathan Senecal - Personal Page
  fr: Jonathan Senecal - Page Personnelle
keywords: ["cv", "resume", "networking", "r√©seau", "project manager", "gestion de projets", "curriculum vitae", "work", "travail",
          "experience", "guru", "network engineer", "network engineering"]
cv_enabled: true
google_api_key: AIzaSyAEDPnmrPaqwXxmOFC7k6LzJH4xvuv8My8
index:
  en: index.en.html
  fr: index.fr.html
feed: /feed.xml
baseurl: "/"
collections:
  - sections
  - cvsections
url: "https://www.jonathansenecal.com"

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-polyglot

# i18n specific config
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["images", "css"]
parallel_localization: true

exclude: [.vscode, .gitignore]